name: Check with linter on PR


on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pylint
        run: pip install pylint
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt
      - name: Run pylint
        run: pylint taskman
  PythonTest:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/my-pool/providers/my-provider' 
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'
          
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9        
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r requirements-dev.txt           
      - name: Run Pytest
        run: pytest tests -s -v -n 4 --dist=loadfile
      - name: Run Test Coverage
        run: pytest --cov=taskman tests/
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
  SnykPython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9        
      - name: Sync analysis
        uses: snyk/actions/python-3.9@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}      
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
  Publish-Docker-Image:
    needs: [build, PythonTest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry 
      uses: docker/login-action@v1      
      with:
        registry: ghcr.io
        username: "hs-heilbronn-devsecops-ppkv"
        password: ${{ secrets.TEST_SECRET}}
    - name: Build the Docker image
      run:  docker build . --tag ghcr.io/hs-heilbronn-devsecops-ppkv/taskman:latest
    - name: Push the Docker image
      run:  docker push ghcr.io/hs-heilbronn-devsecops-ppkv/taskman:latest
  DeployCloudRun:
   permissions:
      contents: 'read'
      id-token: 'write'
   runs-on: ubuntu-latest
   steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Google Auth
         id: auth
         uses: 'google-github-actions/auth@v0'
         with:
            workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}' 
            service_account: '${{ secrets.SERVICE_ACCOUNT }}'
       - name: Deploy to Cloud Run
         id: deploy
         uses: google-github-actions/deploy-cloudrun@v0
         with:
          service: 'taskman-ppkv'
          region: 'europe-west3'
          # NOTE: If required, update to the appropriate source folder
          source: ./
          allow_unauthenticated: true
          env_vars: |
            BACKEND=memory
